version: "3.9"

services:
  authorization-server:
    build:
      context: . # Set the build context to the workspace root
      dockerfile: ./authorization-server/Dockerfile
    ports:
      - "3033:3033"
    environment:
      RUST_LOG: "info"
    volumes:
      - ./unsafe-private.pem:/app/unsafe-private.pem:ro # Mount unsafe-private.pem as read-only
      - ./public.pem:/app/public.pem:ro # Mount public.pem as read-only

  resource-server:
    build:
      context: . # Set the build context to the workspace root
      dockerfile: ./resource-server/Dockerfile
    ports:
      - "3034:3034"
    environment:
      RUST_LOG: "info"
      AUTHORIZATION_SERVER_URL: "http://authorization-server:3033" # Set the URL to match the authorization-server service
